# Generated by Django 3.0.6 on 2020-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='avartasite.jpg', null=True, upload_to='users/'),
        ),
    ]
